steps:
  - label: 'Check Stylish Haskell'
    command: 'nix-shell --run scripts/buildkite/check-stylish.sh'
    agents:
      system: x86_64-linux

  - label: 'Check nixpkgs-fmt'
    command: 'nix-shell --run scripts/buildkite/check-nixpkgs-fmt.sh'
    agents:
      system: x86_64-linux
